version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/wondyframe" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
